### ISSUE TITLE
Propagation of delay with StopTimeEvent with time only

### ISSUE THREAD

**Issue by gcamp** [google/transit#144] opened 2019-02-20 16:44 UTC
Discussion on https://github.com/google/transit/pull/139/ made me think about a case we were unsure how to handle. 

When a `SCHEDULED` stop time update has a `StopTimeEvent` with only a `time` value and no `delay`, should propagation happens on later stops? 

We have seen agencies (YRT if I remember correctly) assume propagation would be done, but that requires the consumer to check the schedule time for that trip, find the delay and then propagate that delay, which might be very involved for some clients. That's the current behaviour in Transit. 

@barbeau would be interested in your feedback, also curious what Google is doing.

**Comment by abyrd** [comment] 2019-02-20 18:26
My interpretation has been that the delay is propagated, even when that delay is implied by comparing against the schedule time. GTFS-RT is meant to be interpreted relative to static GTFS, so any consumer should have access to the necessary data.

**Comment by barbeau** [comment] 2019-02-20 19:40
My interpretation is the same - when only `time` is provided in a StopTimeUpdate, the consumer is responsible for converting that to a delay by comparing it to the GTFS schedule and then propagating that delay value.  This is OneBusAway's behavior.

I did include some text specifically calling this behavior out (although in the context of propagating predictions across trips in the same block) in my proposal at https://github.com/google/transit/pull/110.

I'll ask Google for it's behavior.

**Comment by barbeau** [comment] 2019-02-22 15:21
Google has confirmed that they have the same behavior - `time` is converted to `delay` by comparing it to the GTFS schedule and then that computed delay is propagated.

Because we're touching this same text in #139, I added a commit to further clarify this in that pull request - https://github.com/google/transit/pull/139/commits/8a0e00336f39c6dabe6cea3ade90cc0ba9fd7b06.

So, I'm going to close this issue in favor of handling it within #139.  I'll add a comment there too.

**Closed by barbeau** 2019-02-22 15:21 UTC
