### ISSUE TITLE
Clarify implied timezone for time values in stop_times.txt

### ISSUE THREAD

**Issue by e-lo** [google/transit#322] opened 2022-04-28 23:41 UTC
As a transit provider operating in multi-timezones, Amtrak needs GTFS to be more clear (and consistent) on what time zone the values in `stop_times.txt` refer to.

Current [stop_times.arrival_time](http://gtfs.org/schedule/reference/#stop_timestxt) definition:

> Arrival time at a specific stop for a specific trip on a route. If there are not separate times for arrival and departure at a stop, enter the same value for arrival_time and departure_time. For times occurring after midnight on the service day, enter the time as a value greater than 24:00:00 in HH:MM:SS *local time* for the day on which the trip schedule begins.

The above definition, with use of the word "local" implies that stop_times.txt should use the time zone of the local stop.  However, the `stop.stop_timezone` definition clearly states that if used, that `stop_times` shoudl refer to `agency.agency_timezone`. 

Excerpt of current [stops.stop_timezone](https://gtfs.org/reference/static/#stopstxt) definition:

> If stop_timezone values are provided, the times in [stop_times.txt](https://gtfs.org/reference/static/#stop_timetxt) should be entered as the time since midnight in the timezone specified by agency.agency_timezone.

## Example Problem
Amtrak's Southwest Chief Route travels between Kingman AZ (KNG) and Needles CA (NDL):

Amtrak has implemented the following: 

`agency.agency_timezone` is set to Eastern
`stops.stop_timezone` is set to Mountain for KNG and Pacific for NDL
`stop_times.departure_time` for KNG is specified as 12:28 AM (Mountain Time)
`stop_times.arrival_time` for NDL is specified as 12:26 AM (Pacific Time)

...which results in the validator giving a too-fast travel warning ([See this issue in the GTFS Validator Repository](https://github.com/MobilityData/gtfs-validator/issues/1110)

## Proposed Solution

Clarify definition of `arrival_time` and `departure_time` in  [`stop_times.txt`](http://gtfs.org/schedule/reference/#stop_timestxt) and Time term definition as follows

[Field Type: Time](https://gtfs.org/reference/static/#term-definitions)
Time in the HH:MM:SS format (H:MM:SS is also accepted). The time is measured from "noon minus 12h" of the service day (effectively midnight except for days on which daylight savings time changes occur) **in the time zone specified by agency_timezone. in agency.txt** For times occurring after midnight, enter the time as a value greater than 24:00:00 in HH:MM:SS ~local time~ for the day on which the trip schedule begins.
Example: 14:30:00 for 2:30PM or 25:35:00 for 1:35AM on the next day.

[`stop_times.arrival_time`](https://gtfs.org/reference/static/#term-definitions)
Arrival time at a specific stop for a specific trip on a route **in the time zone specified by agency_timezone. ** If there are not separate times for arrival and departure at a stop, enter the same value for arrival_time and departure_time.  For times occurring after midnight on the service day, enter the time as a value greater than 24:00:00 in HH:MM:SS ~local time~ for the day on which the trip schedule begins....

...and ditto with `departure_time`

**Comment by asvechnikov2** [comment] 2022-05-04 06:33
Hi @e-lo, thanks for bringing this up! I can confirm that Google uses `agency_timezone` for all `stop_times` times.  Please let me know if I can clarify any other question you might have.

Do you think we can also propose the next change as part of this issue?

> If stop_timezone values are provided, the times in [stop_times.txt](https://gtfs.org/reference/static/#stop_timetxt) ~should~ **must** be entered ~as the time since midnight~ in the timezone specified by agency.agency_timezone.

**Comment by MartinH-open** [comment] 2022-05-07 22:56
I'm new to GTFS and I find it weird : for me a time without date is useless and a date without timezone is useless too.
We should use only fully qualified date-time-timezone (in future GTFS versions). 
With fully qualified values you can pick any timezone you want and even select it depending on local daylight saving time preferences. (see https://en.wikipedia.org/wiki/ISO_8601)

**Comment by asvechnikov2** [comment] 2022-05-12 04:39
Thanks @MartinH-open! The main problem with using times with date and timezone is the format of data, it's possible to define the same trip to run on different dates which significantly reduce amount of data. We should take a look at the ways to reduce confusions. 

cc: @isabelle-dr

**Comment by e-lo** [comment] 2022-05-12 21:24
PR Opened: #328

**Comment by derhuerst** [comment] 2022-05-13 19:00
Conceptually, is there a reason why Google doesn't use the `stop_timezone`? It makes a lot of sense to use it, right?
It also cleanly handles [weird exceptions like Arizona's DST handling](https://en.wikipedia.org/wiki/Time_in_Arizona), whereas using `agency_timezone` *only* does not.

**Comment by asvechnikov2** [comment] 2022-05-18 00:36
Hi @derhuerst, I don't know why it was done this way historically. I can see some potential issues with using `stop_timezone`. 

* Some GTFS feeds may be a concatenation (or merged version) of multiple other feeds corresponding to different agencies. Since `stop_timezone` is an optional field merging/concatenation must be done with some level of cautiousness to make sure that times are presented consistently.
* Another case is when a trip stops in multiple timezones and daylight saving doesn't happen simultaneously across different timezones. This means that a new trip must be created for each combination of timezones, which will also open space for misinterpretations and errors.

I think one of possible ways to get rid of such problems is to define all times using UTC, however, it's not clear how this would affect service dates. So probably operating in a context of an agency timezone isn't that bad.

**Comment by derhuerst** [comment] 2022-05-22 12:03
> * Some GTFS feeds may be a concatenation (or merged version) of multiple other feeds corresponding to different agencies. Since `stop_timezone` is an optional field merging/concatenation must be done with some level of cautiousness to make sure that times are presented consistently.

Can you give an example of what could go wrong in this process?

> * Another case is when a trip stops in multiple timezones and daylight saving doesn't happen simultaneously across different timezones. This means that a new trip must be created for each combination of timezones, which will also open space for misinterpretations and errors.

Does it? I'd rather say the opposite: If for such a trip only `agency_timezone` is defined, it is hard to know which timezone to apply to each stop, as their regions *do* have different timezone offsets; If each stop has a `stop_timezone` however, it is very clear how to convert (and display to users, subsequently) the stop time to an epoch/UNIX timestamp.

> I think one of possible ways to get rid of such problems is to define all times using UTC, however, it's not clear how this would affect service dates. So probably operating in a context of an agency timezone isn't that bad.

GTFS' current design has the disadvantage that agencies can't "1-to-1-map" their schedules, which AFAIK are usually planned using & defined in wall clock times, to GTFS trips & stop times; It seems like this was an explicit design goal.

Following this assumption, by changing all stop times to be in UTC, you effectively *shift* the interpretation/conversion problem to the producer, but don't get rid of it! GTFS producers, sometimes without IT-literate staff, will have to do this, instead of (mostly?) software/data engineers.

**Comment by derhuerst** [comment] 2023-04-07 12:46
To make sure we're on the same page, let's consider a specific example. Please check if my process is correct:

1. I'm using the [Amtrak 2023-04-01 GTFS Feed](https://github.com/MobilityData/mobility-database-catalogs/blob/c90d0c7373e6bff3328ad7f5893171827e81edce/catalogs/sources/gtfs/schedule/us-unknown-amtrak-gtfs-11.json#L16-L17) (`feed_info.feed_start_date` says `20230401`, so I assume this is the authoring date).
2. I look at trip `trip_id = 192854940`, which
	- departs at `NYP` (*Ny Moynihan Train Hall At Penn Station*, with `stop_timezone = America/New_York`) with `departure_time = 10:15:00`, and
	- arrives at `GRV` (*Greenville Amtrak Station*, with `stop_timezone = America/New_York`) with `arrival_time = 29:24:00`.
3. To compute the *absolute* arrival date+time at `GRV`, I
	a. Pick the reference date+time: `date = 2023-11-26` at noon with `agency_timezone = America/New_York` (yielding `2023-11-26T12:00-05`), then subtract 12 hours, which yields`2023-11-26T00:00-05`.
	b. Apply the `arrival_time = 29:24:00` to the reference date+time (`2023-11-26T00:00-05`), which **yields `2023-11-27T05:24-05`**. I *do not* apply `stop_timezone = America/Chicago` (by resetting the reference "wall clock time", yielding `2023-11-26T00:00-06`, then applying the `arrival_time`, yielding `2023-11-27T05:24-06`).
4. To compute the *local* "wall clock time" of the arrival at `GRV`, I transform the *absolute* date+time (`2023-11-27T05:24-05`) to `stop_timezone = America/Chicago` (`2023-11-27T04:24-06` and extract the time part, yielding `4:24am`.

The process above assumes that
- `agency_timezone` applies to *all* `stop_times` entries of all its trips, and that
- `stop_timezone` is purely intended for computing the local "wall clock time" of an arrival/departure.

**Comment by tzujenchanmbd** [comment] 2023-04-18 15:29
Hello, this is Tzu-Jen, the new data analyst at MobilityData. I am trying to understand the discussion and hope to make appropriate modifications to the spec.

I tried to generate an Amtrak trip from CHI (Chicago Union Station) to BOS (Boston South Station) on Google Maps on Android to see how Google presents cross-time zone trips. Here are my findings:
- Searched routes on Tuesday, a trip of Lake Shore Limited presented on the trip options page, departing at **9:30pm (Tues)** and arriving at **8:32pm (Wed)**. The traversal time shows **22 hours** and 2 mins, so there is 1 hour offset.
- Searched a trip in GTFS that matches the example above, using the Amtrak 2023-04-01 GTFS Feed  as well
    * In stop_times.txt, a trip (trip id: 4482875809) departs from CHI at **22:30:00** and arrives at BOS at **44:32:00**
    * agency.agency_timezone = America/New_York
    * stops.stop_timezone for CHI = America/Chicago, for BOS = America/New_York

It appears that in this example, agency_timezone is indeed used in stop_times.txt (22:30:00), but when presented to users, it is offset by 1 hour ("wall clock time" 9:30pm). In addition, I also searched an Amtrak trip from Seattle to Chicago, and Google Maps showed 2 hours offset as expected.

Therefore, it seems Google uses agency_timezone for entries in stop_times.txt, but still consider timezone for each station (perhaps stop_timezone?) when presenting info to users, which is in line with the following assumption mentioned by Jannis.

> * `agency_timezone` applies to _all_ `stop_times` entries of all its trips, and that
> * `stop_timezone` is purely intended for computing the local "wall clock time" of an arrival/departure.

@asvechnikov2 could you help confirm if it's correct? Looks like we are on the same page?

**Comment by bdferris-v2** [comment] 2023-04-18 20:14
@tzujenchanmbd that matches my understanding as well.  Per the spec for `stops.txt - stop_timezone`:

> If `stop_timezone` values are provided, the times in `stop_times.txt` should be entered as the time since midnight in the timezone specified by `agency.agency_timezone`.

Seems pretty clear on the semantics to me?

**Comment by tzujenchanmbd** [comment] 2023-04-19 21:49
@bdferris-v2 agree that the semantics for `stops.stop_timezone` are pretty clear. In previous discussion there seemed to be some confusion about how Google uses `stops.stop_timezone`, but I think it's all clear now. Thank you for your confirmation!

The original comment from @e-lo pointed out the use of the word "local" implies that `stop_times.txt` should use the time zone of the local stop, which is inconsistent with the `stops.stop_timezone` definition. This also caused problems for Amtrak at the time. As per previous discussion, it seems that everyone agrees that Elizabeth's proposed solution can better clarify the definition for `Field Type: Time`,`stop_times.arrival_time`, and `stop_times.departure_time`.

Before opening a PR, I would like to make sure this modification will not have potential negative impact on any consumers, i.e. no consumers currently regard the times entered in `stop_times.txt` as being in the local time zone.

@gcamp, @flocsy, @leonardehrenfried could you please check if the proposed solution looks good to you as well? Thanks!

**Comment by flocsy** [comment] 2023-04-20 10:44
Moovit is OK with the change

**Closed** 2023-08-01 16:17 UTC
Labels: GTFS Schedule
